name: napari
channels:
  - conda-forge
  - manics
dependencies:
  - python=3.6
  - pip
  - websockify=0.9.0
  - zeroc-ice-python=3.6.5
  # https://github.com/napari/napari/blob/v0.2.2/requirements/default.txt
  - dask
  - zarr
  - fsspec
  - imageio
  - ipykernel
  - numpy
  - qtpy
  - qtconsole
  - scipy
  - scikit-image
  - vispy
  - ipython
  - backcall
  - pyopengl
  - pyside2
  - wrapt
  - numpydoc
  - pip:
    # Recent jupyter-server-proxy to load vnc_lite.html instead of /
    # https://github.com/jupyterhub/jupyter-server-proxy/pull/151
    - https://github.com/jupyterhub/jupyter-server-proxy/archive/0e67e1afd0bab1342443f13bd147a2f8c682e9e0.zip
    - https://github.com/ome/omero-py/archive/v5.6.dev1.zip
    # The conda pyside2 package doesn't appear in pip list so napari tries to reinstall it
    # https://github.com/conda-forge/pyside-feedstock/issues/35
    # napari==0.2.2
    # Manually install in postBuild instead with --no-dependencies
